"""Transactional persistence port for Mission creation."""

from __future__ import annotations

from typing import Protocol, Self

from research_forge.domain.artifact import ArtifactRegistration
from research_forge.domain.approval import Approval
from research_forge.domain.execution import Operation
from research_forge.domain.evidence import Claim, EvidenceLink, MetricRecord
from datetime import datetime

from research_forge.domain.mission import Attempt, AuditEvent, Mission, OutboxEvent, Task


class UnitOfWork(Protocol):
    """Persists business state, audit events, and outbox events atomically."""

    def __enter__(self) -> Self: ...

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: object | None,
    ) -> bool | None: ...

    def add_mission(self, mission: Mission) -> None: ...

    def add_task(self, task: Task) -> None: ...

    def add_attempt(self, attempt: Attempt) -> None: ...

    def add_audit_event(self, event: AuditEvent) -> None: ...

    def add_outbox_event(self, event: OutboxEvent) -> None: ...

    def add_operation(self, operation: Operation) -> None: ...

    def add_artifact(self, registration: ArtifactRegistration) -> None: ...

    def add_metric(self, metric: MetricRecord) -> None: ...

    def add_claim(self, claim: Claim) -> None: ...

    def add_evidence_link(self, link: EvidenceLink) -> None: ...

    def add_bundle(self, mission_id: str, artifact: ArtifactRegistration) -> None: ...

    def add_approval(self, approval: Approval) -> None: ...

    def get_mission(self, mission_id: str) -> Mission | None: ...

    def get_task(self, task_id: str) -> Task | None: ...

    def get_tasks_for_mission(self, mission_id: str) -> tuple[Task, ...]: ...

    def get_attempt(self, attempt_id: str) -> Attempt | None: ...

    def get_attempts_for_task(self, task_id: str) -> tuple[Attempt, ...]: ...

    def get_operation_by_idempotency_key(self, idempotency_key: str) -> Operation | None: ...

    def get_artifact_by_operation_id(self, operation_id: str) -> ArtifactRegistration | None: ...

    def get_artifacts_for_attempt(self, attempt_id: str) -> tuple[ArtifactRegistration, ...]: ...

    def get_metric_by_attempt_id(self, attempt_id: str) -> MetricRecord | None: ...

    def get_claims_for_mission(self, mission_id: str) -> tuple[Claim, ...]: ...

    def get_evidence_for_claim(self, claim_id: str) -> tuple[EvidenceLink, ...]: ...

    def get_bundle(self, mission_id: str) -> ArtifactRegistration | None: ...

    def get_approval(self, approval_id: str) -> Approval | None: ...

    def get_approvals_for_mission(self, mission_id: str) -> tuple[Approval, ...]: ...

    def get_unpublished_outbox_events(self, limit: int) -> tuple[OutboxEvent, ...]: ...

    def mark_outbox_event_published(self, event_id: str, published_at: datetime) -> None: ...

    def commit(self) -> None: ...

    def rollback(self) -> None: ...
